### PR TITLE
Merge sgmap master openfisca next

### PR DESCRIPTION
**Pull request by fpagnoux**
I'm Checking impacts on the mapping. PR to come on mes-aides-api

### CODE REVIEW

**Comment by MattiSG** [comment]
:+1: great way to do it!!

I'll put in traces of the discussion we had by mail.

**Comment by MattiSG** [comment]
Renames that impact mes-aides:

`agem` => `age_en_mois`
`inv` => `invalide`
`salbrut` => `salaire_brut`

**Comment by benjello** [comment]
@fpagnoux @MattiSG 
Beware: salbrut which become salaire_brut do not impact you: it is only for decomposition etc

**Comment by MattiSG** [comment]
@benjello Thanks for the heads up!!

**Comment by MattiSG** [comment]
This PR **must not** be merged through the web interface, but as a fast-forward through the CLI.
Otherwise, we will add merge commits that will make our history diverge from openfisca/openfisca-france's.

**Comment by fpagnoux** [comment]
All commits were merged to Next. Temporarily using the `prod` branch until openfisca/openfisca-france#223 is fixed.

**Pull request closed without merging**
